# Generated by Django 5.0.3 on 2024-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='psw',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('---', '---'), ('MAS', 'Masculino'), ('FEM', 'Femenino')], default='xxx', max_length=12),
        ),
    ]
