# Generated by Django 5.0.3 on 2024-04-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_usuario_psw_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Femenino')], default='xxx', max_length=12),
        ),
    ]
