# Generated by Django 5.0.3 on 2024-04-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comentario_delete_usuario_articulo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.articulo'),
            preserve_default=False,
        ),
    ]
