# Generated by Django 5.0.3 on 2024-04-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comentario_id_comentario_alter_comentario_nom_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='comentario',
        ),
    ]
