# Generated by Django 5.0.3 on 2024-04-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_articulo_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='activo',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articulo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nom_usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
