# Generated by Django 5.0.3 on 2024-04-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comentario_options_remove_comentario_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
